import { Validators } from '@angular/forms';

import { FormField } from '../interfaces/form-field.interface';

export const HOST_FORM_FIELDS: FormField[] = [
  {
    name: 'businessName',
    label: 'Business Name*',
    placeholder: 'Enter business name',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'numberOfLicense',
    label: 'Number of Licenses*',
    placeholder: 'Enter number of licenses',
    type: 'number',
    validators: [Validators.required],
    inputType: 'autocomplete',
  },
  {
    name: 'generalCategory',
    label: 'General Category*',
    placeholder: 'Enter general category',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'category',
    label: 'Category*',
    placeholder: 'Enter category',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'contactPerson',
    label: 'Contact Person*',
    placeholder: 'Enter contact person',
    type: 'text',
    validators: [],
    inputType: 'input',
  },
  {
    name: 'contactNumber',
    label: 'Contact Number*',
    placeholder: 'Enter contact number',
    type: 'number',
    validators: [],
    inputType: 'input',
  },
  {
    name: 'latitude',
    label: 'Latitude*',
    placeholder: 'Enter latitude',
    type: 'number',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'longitude',
    label: 'Longitude*',
    placeholder: 'Enter longitude',
    type: 'number',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'address',
    label: 'Address*',
    placeholder: 'Enter address',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'city',
    label: 'City*',
    placeholder: 'Enter city',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'state',
    label: 'State*',
    placeholder: 'Enter state',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'region',
    label: 'Region*',
    placeholder: 'Enter region',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'zipCode',
    label: 'Zip Code*',
    placeholder: 'Enter zip code',
    type: 'number',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'timezone',
    label: 'Timezone*',
    placeholder: 'Enter timezone',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
];

export const CREATE_SCREEN_FORM: FormField[] = [
  {
    name: 'screenName',
    label: 'Screen Name*',
    placeholder: 'Enter screen name',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'description',
    label: 'Screen Name*',
    placeholder: 'Enter screen name',
    type: 'text',
    validators: [Validators.required],
    inputType: 'input',
  },
  {
    name: 'screenType',
    label: 'Screen Name*',
    placeholder: 'Click to select Screen Type*',
    type: 'text',
    validators: [Validators.required],
    inputType: 'autocomplete',
  },
];
